// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8MCyPK0xMGo6lGY6P4IaIHfZ5_cCLkQ',
    appId: '1:833261845258:web:e798f3abc0aeab89b498f3',
    messagingSenderId: '833261845258',
    projectId: 'fitbeat-firebase-auth',
    authDomain: 'fitbeat-firebase-auth.firebaseapp.com',
    storageBucket: 'fitbeat-firebase-auth.firebasestorage.app',
    measurementId: 'G-YL6SGVCZFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-r0TJckR_lzLKqTRuYWtiHCg4uO5mTHM',
    appId: '1:833261845258:android:f84712a760b97e83b498f3',
    messagingSenderId: '833261845258',
    projectId: 'fitbeat-firebase-auth',
    storageBucket: 'fitbeat-firebase-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD377iDIiD2N0r96t0udtakm79xsPfat4w',
    appId: '1:833261845258:ios:07f9402fb4f2000ab498f3',
    messagingSenderId: '833261845258',
    projectId: 'fitbeat-firebase-auth',
    storageBucket: 'fitbeat-firebase-auth.firebasestorage.app',
    iosBundleId: 'com.example.fitbeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD377iDIiD2N0r96t0udtakm79xsPfat4w',
    appId: '1:833261845258:ios:07f9402fb4f2000ab498f3',
    messagingSenderId: '833261845258',
    projectId: 'fitbeat-firebase-auth',
    storageBucket: 'fitbeat-firebase-auth.firebasestorage.app',
    iosBundleId: 'com.example.fitbeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs8MCyPK0xMGo6lGY6P4IaIHfZ5_cCLkQ',
    appId: '1:833261845258:web:864ef54197a89c36b498f3',
    messagingSenderId: '833261845258',
    projectId: 'fitbeat-firebase-auth',
    authDomain: 'fitbeat-firebase-auth.firebaseapp.com',
    storageBucket: 'fitbeat-firebase-auth.firebasestorage.app',
    measurementId: 'G-FX2ZBQ8P8W',
  );
}
